server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://intobook.cypu9mlwgsym.us-east-1.rds.amazonaws.com:3306/intobook?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: root
    password: rla00605

    security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: d65bd1ef2f9d2f8056ef153efcc983e7
              client-secret: XJnjnScvebxqQNWEwtohdUMI9x17WTln
              redirect-uri: http://intobook:8080/login/oauth2/code/kakao
              client-authentication-method: POST
              authorization-grant-type: authorization_code
              scope: profile_nickname, account_email
              client-name: Kakao

          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

redirect:
  url: https://intobook.kro.kr